name: easyrecipe
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter  
  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.14
  image_picker: ^1.0.7
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  firebase_auth: ^5.5.4
  google_sign_in: ^6.3.0
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8 
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.0
  shared_preferences: ^2.2.2
  package_info_plus: ^8.0.0
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo_en.png
    - assets/logo_zh.png
    - assets/onboard_add.png
    - assets/onboard_cloud.png
    - assets/sample1.jpg
    - assets/sample2.jpg
    - assets/sample3.jpg
    - assets/sample4.jpg
    - assets/sample5.jpg
    - assets/sample6.jpg
    - assets/sample7.jpg
    - assets/sample8.jpg
    - assets/sample9.jpg
    - assets/sample10.jpg

  generate: true

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo_en.png
  android: true
  ios: false
